### ISSUE TITLE
Changing the font

### ISSUE THREAD

**Issue by DutchPete** [sethyuan/logseq-plugin-tocgen#68]
In the ToC I would like to change the H2 font to uppercase, i.e. `text-transform: uppercase;` and for the H3 header I would like `font-variant: small-caps;`.

I tried to find the selector via the dev tools but could not.
Please advise.

**Comment by sethyuan** [comment]
I updated a version that includes this level information.

![image](https://github.com/sethyuan/logseq-plugin-tocgen/assets/3410293/507df9a7-b9c0-4c26-a04f-2c6fce597216)

**Comment by DutchPete** [comment]
Thanks for that.

If I do
```
.kef-tocgen-block {
  text-transform: uppercase !important;
}
```
it transforms everything to upper case. How can I target specifically h2?
I tried adding `.h2.uniline-block` but that does not work.

**Comment by sethyuan** [comment]
You have to write rules like this:

```css
.kef-tocgen-block[data-level="1"] {
  text-transform: uppercase;
}
.kef-tocgen-block[data-level="2"] {
  font-variant: small-caps;
}
```
